/* ================================================
   MÓDULO DE VEHÍCULOS — DATOS MOCK
   car-mock.data.ts — Pooking Interface
   Modela el contrato API RedCar V2.0.0
   ================================================ */

import { VehicleItem, Localizacion, Extra, Categoria } from './car.models';

// ─── Localizaciones ────────────────────────────────────────────────────────
export const LOCALIZACIONES_MOCK: Localizacion[] = [
  {
    idLocalizacion: 1,
    codigo: 'LOC-001',
    nombre: 'Aeropuerto Quito',
    direccion: 'Av. Interoceánica S/N, Tababela',
    telefono: '02-395-1000',
    correo: 'quito.aeropuerto@redcar.com',
    horarioAtencion: 'Lunes a Domingo 06:00 - 22:00',
    zonaHoraria: 'America/Guayaquil',
    estado: 'ACT',
    ciudad: { idCiudad: 1, nombre: 'Quito' },
  },
  {
    idLocalizacion: 2,
    codigo: 'LOC-002',
    nombre: 'Centro Quito',
    direccion: 'Av. Amazonas N37-29 y Unión Nacional',
    telefono: '02-290-5500',
    correo: 'quito.centro@redcar.com',
    horarioAtencion: 'Lunes a Sábado 08:00 - 20:00',
    zonaHoraria: 'America/Guayaquil',
    estado: 'ACT',
    ciudad: { idCiudad: 1, nombre: 'Quito' },
  },
  {
    idLocalizacion: 3,
    codigo: 'LOC-003',
    nombre: 'Aeropuerto Guayaquil',
    direccion: 'Av. de las Américas S/N, Guayaquil',
    telefono: '04-216-9000',
    correo: 'gye.aeropuerto@redcar.com',
    horarioAtencion: 'Lunes a Domingo 05:00 - 23:00',
    zonaHoraria: 'America/Guayaquil',
    estado: 'ACT',
    ciudad: { idCiudad: 2, nombre: 'Guayaquil' },
  },
  {
    idLocalizacion: 4,
    codigo: 'LOC-004',
    nombre: 'Centro Guayaquil',
    direccion: 'Av. 9 de Octubre 1900 y García Avilés',
    telefono: '04-245-8800',
    correo: 'gye.centro@redcar.com',
    horarioAtencion: 'Lunes a Sábado 08:00 - 20:00',
    zonaHoraria: 'America/Guayaquil',
    estado: 'ACT',
    ciudad: { idCiudad: 2, nombre: 'Guayaquil' },
  },
  {
    idLocalizacion: 5,
    codigo: 'LOC-005',
    nombre: 'Aeropuerto Cuenca',
    direccion: 'Av. España S/N, Cuenca',
    telefono: '07-286-2203',
    correo: 'cuenca.aeropuerto@redcar.com',
    horarioAtencion: 'Lunes a Domingo 06:00 - 22:00',
    zonaHoraria: 'America/Guayaquil',
    estado: 'ACT',
    ciudad: { idCiudad: 3, nombre: 'Cuenca' },
  },
];

// ─── Categorías ────────────────────────────────────────────────────────────
export const CATEGORIAS_MOCK: Categoria[] = [
  {
    idCategoria: 1,
    codigo: 'ECO',
    nombre: 'Económico',
    descripcion: 'Vehículos compactos ideales para ciudad',
    estado: 'ACT',
  },
  {
    idCategoria: 2,
    codigo: 'SUV',
    nombre: 'SUV',
    descripcion: 'Vehículos todo terreno para familia',
    estado: 'ACT',
  },
  {
    idCategoria: 3,
    codigo: 'LUX',
    nombre: 'Lujo',
    descripcion: 'Vehículos premium de alta gama',
    estado: 'ACT',
  },
  {
    idCategoria: 4,
    codigo: 'VAN',
    nombre: 'Van / Minivan',
    descripcion: 'Vehículos de gran capacidad para grupos',
    estado: 'ACT',
  },
  {
    idCategoria: 5,
    codigo: 'CMP',
    nombre: 'Camioneta',
    descripcion: 'Camionetas doble cabina para trabajo y aventura',
    estado: 'ACT',
  },
];

// ─── Extras ────────────────────────────────────────────────────────────────
export const EXTRAS_MOCK: Extra[] = [
  {
    idExtra: 1,
    codigo: 'GPS',
    nombre: 'GPS',
    descripcion: 'Navegador GPS integrado con mapas actualizados',
    valorFijo: 5.00,
    estado: 'ACT',
    icono: 'location_on',
  },
  {
    idExtra: 2,
    codigo: 'SILLA-BEBE',
    nombre: 'Silla de bebé',
    descripcion: 'Silla de seguridad para niños hasta 18 kg',
    valorFijo: 7.50,
    estado: 'ACT',
    icono: 'child_care',
  },
  {
    idExtra: 3,
    codigo: 'SEG-EXTRA',
    nombre: 'Seguro complementario',
    descripcion: 'Cobertura adicional sin franquicia para colisión y robo',
    valorFijo: 12.00,
    estado: 'ACT',
    icono: 'shield',
  },
  {
    idExtra: 4,
    codigo: 'CHOFER',
    nombre: 'Chofer profesional',
    descripcion: 'Conductor certificado disponible todo el día',
    valorFijo: 45.00,
    estado: 'ACT',
    icono: 'person',
  },
  {
    idExtra: 5,
    codigo: 'WIFI',
    nombre: 'Wi-Fi portátil',
    descripcion: 'Router 4G LTE con datos ilimitados durante el alquiler',
    valorFijo: 8.00,
    estado: 'ACT',
    icono: 'wifi',
  },
];

// ─── Vehículos ─────────────────────────────────────────────────────────────
const locQ = LOCALIZACIONES_MOCK[0]; // Aeropuerto Quito
const locG = LOCALIZACIONES_MOCK[2]; // Aeropuerto Guayaquil
const locC = LOCALIZACIONES_MOCK[4]; // Aeropuerto Cuenca

const disp = (dias: number) => ({
  fechaRecogida: '2026-06-01T08:00:00Z',
  fechaDevolucion: `2026-06-0${1 + dias}T10:00:00Z`,
  cantidadDias: dias,
  disponible: true,
});

const precio = (baseDia: number, dias: number) => {
  const sub = +(baseDia * dias).toFixed(2);
  const iv = +(sub * 0.15).toFixed(2);
  return { precioBaseDia: baseDia, subtotalVehiculo: sub, iva: iv, total: +(sub + iv).toFixed(2) };
};

export const VEHICULOS_MOCK: VehicleItem[] = [
  // ── 1. Chevrolet Sail — Económico ──
  {
    idVehiculo: 1,
    codigoInterno: 'VEH-001',
    marca: 'Chevrolet',
    modelo: 'Sail',
    anio: 2023,
    color: 'Blanco',
    imagenUrl: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80',
    transmision: 'MANUAL',
    combustible: 'GASOLINA',
    capacidadPasajeros: 5,
    capacidadMaletas: 2,
    numeroPuertas: 4,
    aireAcondicionado: true,
    estado: 'ACT',
    localizacion: locQ,
    categoria: CATEGORIAS_MOCK[0],
    disponibilidad: disp(3),
    precio: precio(28, 3),
  },
  // ── 2. Toyota Corolla — Económico ──
  {
    idVehiculo: 2,
    codigoInterno: 'VEH-002',
    marca: 'Toyota',
    modelo: 'Corolla',
    anio: 2024,
    color: 'Plata',
    imagenUrl: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80',
    transmision: 'AUTOMATICA',
    combustible: 'GASOLINA',
    capacidadPasajeros: 5,
    capacidadMaletas: 2,
    numeroPuertas: 4,
    aireAcondicionado: true,
    estado: 'ACT',
    localizacion: locQ,
    categoria: CATEGORIAS_MOCK[0],
    disponibilidad: disp(3),
    precio: precio(35, 3),
  },
  // ── 3. Suzuki Grand Vitara — SUV ──
  {
    idVehiculo: 3,
    codigoInterno: 'VEH-003',
    marca: 'Suzuki',
    modelo: 'Grand Vitara',
    anio: 2023,
    color: 'Gris',
    imagenUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80',
    transmision: 'AUTOMATICA',
    combustible: 'GASOLINA',
    capacidadPasajeros: 5,
    capacidadMaletas: 3,
    numeroPuertas: 4,
    aireAcondicionado: true,
    estado: 'ACT',
    localizacion: locQ,
    categoria: CATEGORIAS_MOCK[1],
    disponibilidad: disp(3),
    precio: precio(48, 3),
  },
  // ── 4. Ford Explorer — SUV ──
  {
    idVehiculo: 4,
    codigoInterno: 'VEH-004',
    marca: 'Ford',
    modelo: 'Explorer',
    anio: 2024,
    color: 'Negro',
    imagenUrl: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&q=80',
    transmision: 'AUTOMATICA',
    combustible: 'GASOLINA',
    capacidadPasajeros: 7,
    capacidadMaletas: 4,
    numeroPuertas: 4,
    aireAcondicionado: true,
    estado: 'ACT',
    localizacion: locG,
    categoria: CATEGORIAS_MOCK[1],
    disponibilidad: disp(3),
    precio: precio(65, 3),
  },
  // ── 5. Mercedes-Benz Clase C — Lujo ──
  {
    idVehiculo: 5,
    codigoInterno: 'VEH-005',
    marca: 'Mercedes-Benz',
    modelo: 'Clase C',
    anio: 2024,
    color: 'Negro',
    imagenUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80',
    transmision: 'AUTOMATICA',
    combustible: 'GASOLINA',
    capacidadPasajeros: 5,
    capacidadMaletas: 3,
    numeroPuertas: 4,
    aireAcondicionado: true,
    estado: 'ACT',
    localizacion: locQ,
    categoria: CATEGORIAS_MOCK[2],
    disponibilidad: disp(3),
    precio: precio(120, 3),
  },
  // ── 6. BMW Serie 5 — Lujo ──
  {
    idVehiculo: 6,
    codigoInterno: 'VEH-006',
    marca: 'BMW',
    modelo: 'Serie 5',
    anio: 2024,
    color: 'Blanco',
    imagenUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
    transmision: 'AUTOMATICA',
    combustible: 'GASOLINA',
    capacidadPasajeros: 5,
    capacidadMaletas: 3,
    numeroPuertas: 4,
    aireAcondicionado: true,
    estado: 'ACT',
    localizacion: locG,
    categoria: CATEGORIAS_MOCK[2],
    disponibilidad: disp(3),
    precio: precio(140, 3),
  },
  // ── 7. Kia Carnival — Van ──
  {
    idVehiculo: 7,
    codigoInterno: 'VEH-007',
    marca: 'Kia',
    modelo: 'Carnival',
    anio: 2023,
    color: 'Gris Oscuro',
    imagenUrl: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80',
    transmision: 'AUTOMATICA',
    combustible: 'GASOLINA',
    capacidadPasajeros: 8,
    capacidadMaletas: 5,
    numeroPuertas: 4,
    aireAcondicionado: true,
    estado: 'ACT',
    localizacion: locC,
    categoria: CATEGORIAS_MOCK[3],
    disponibilidad: disp(3),
    precio: precio(75, 3),
  },
  // ── 8. Toyota Hilux — Camioneta ──
  {
    idVehiculo: 8,
    codigoInterno: 'VEH-008',
    marca: 'Toyota',
    modelo: 'Hilux',
    anio: 2023,
    color: 'Blanco',
    imagenUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    transmision: 'MANUAL',
    combustible: 'DIESEL',
    capacidadPasajeros: 5,
    capacidadMaletas: 4,
    numeroPuertas: 4,
    aireAcondicionado: true,
    estado: 'ACT',
    localizacion: locC,
    categoria: CATEGORIAS_MOCK[4],
    disponibilidad: disp(3),
    precio: precio(58, 3),
  },
];
